server:
  port: 8081

spring:
  application:
    name: ms-clientes
  datasource:
    url: jdbc:postgresql://localhost:5432/clientesdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
