server:
  port: 8082

spring:
  application:
    name: ms-cuentas
  datasource:
    url: jdbc:postgresql://postgres-db:5432/cuentasdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cliente-service:
  url: http://ms-clientes:8081/clientes
